baseURL = "https://itsjan.github.io/CS-EJ4104/"
languageCode = "en-us"
#title = "About John Doe "
theme = "hugo-vitae"
mainSections = ["post"]

 [[menu.main]]
	name = "Blog"
	url = "/post/"

[[menu.main]]
	name = "About"
	url = "/"
